import Jeans from "../../assets/jeans.png";
import Hoodie from "../../assets/hoodie.png";
import LeatherJacket from "../../assets/leather-jacket.png";
import Skirt from "../../assets/skirt.png";
import TShirt from "../../assets/tshirt.png";
import Sleepsuit from "../../assets/sleepsuit.png";
import Shirt from "../../assets/shirt.png";
import Dress from "../../assets/dress.png";
import Skater from "../../assets/skater.png";
import Sweater from "../../assets/sweater.png";
import BabyShirt from "../../assets/baby-shirt.png";
import ShirtDress from "../../assets/shirt-dress.png";

const products = [
  // ---------- Mens ----------
  {
    id: 1,
    name: "Sports T-shirt",
    Image: TShirt,
    price: 647,
    oldPrice: 896,
    onSale: true,
    NewArrival: false,
    cate: "Mens",
  },
  {
    id: 2,
    name: "Casual Jeans",
    Image: Jeans,
    price: 1020,
    oldPrice: 1394,
    onSale: false,
    NewArrival: true,
    cate: "Mens",
  },
  {
    id: 3,
    name: "Winter Hoodie",
    Image: Hoodie,
    price: 1245,
    oldPrice: 1743,
    onSale: true,
    NewArrival: false,
    cate: "Mens",
  },
  {
    id: 4,
    name: "Leather Jacket",
    Image: LeatherJacket,
    price: 2988,
    oldPrice: 3735,
    onSale: false,
    NewArrival: true,
    cate: "Mens",
  },
  {
    id: 5,
    name: "Formal Shirt",
    Image: Shirt,
    price: 747,
    oldPrice: 1120,
    onSale: true,
    NewArrival: false,
    cate: "Mens",
  },
  {
    id: 6,
    name: "Wool Sweater",
    Image: Sweater,
    price: 1145,
    oldPrice: 1518,
    onSale: false,
    NewArrival: true,
    cate: "Mens",
  },
  {
    id: 7,
    name: "Graphic T-shirt",
    Image: TShirt,
    price: 572,
    oldPrice: 772,
    onSale: true,
    NewArrival: false,
    cate: "Mens",
  },
  {
    id: 8,
    name: "Slim Fit Jeans",
    Image: Jeans,
    price: 1070,
    oldPrice: 1394,
    onSale: false,
    NewArrival: true,
    cate: "Mens",
  },

  // ---------- Women ----------
  {
    id: 9,
    name: "Summer Dress",
    Image: Dress,
    price: 896,
    oldPrice: 1269,
    onSale: false,
    NewArrival: true,
    cate: "Women",
  },
  {
    id: 10,
    name: "Mini Skirt",
    Image: Skirt,
    price: 498,
    oldPrice: 747,
    onSale: true,
    NewArrival: false,
    cate: "Women",
  },
  {
    id: 11,
    name: "Shirt Dress",
    Image: ShirtDress,
    price: 996,
    oldPrice: 1369,
    onSale: false,
    NewArrival: true,
    cate: "Women",
  },
  {
    id: 12,
    name: "Casual Skater",
    Image: Skater,
    price: 971,
    oldPrice: 1269,
    onSale: true,
    NewArrival: false,
    cate: "Women",
  },
  {
    id: 13,
    name: "Knitted Sweater",
    Image: Sweater,
    price: 1145,
    oldPrice: 1518,
    onSale: false,
    NewArrival: true,
    cate: "Women",
  },
  {
    id: 14,
    name: "Floral Dress",
    Image: Dress,
    price: 1394,
    oldPrice: 1889,
    onSale: true,
    NewArrival: false,
    cate: "Women",
  },
  {
    id: 15,
    name: "High Waist Skirt",
    Image: Skirt,
    price: 722,
    oldPrice: 1020,
    onSale: false,
    NewArrival: true,
    cate: "Women",
  },
  {
    id: 16,
    name: "Long Sleeve Shirt Dress",
    Image: ShirtDress,
    price: 1120,
    oldPrice: 1518,
    onSale: true,
    NewArrival: false,
    cate: "Women",
  },

  // ---------- Kids ----------
  {
    id: 17,
    name: "Baby Sleepsuit",
    Image: Sleepsuit,
    price: 398,
    oldPrice: 647,
    onSale: true,
    NewArrival: false,
    cate: "Kids",
  },
  {
    id: 18,
    name: "Kids Hoodie",
    Image: Hoodie,
    price: 647,
    oldPrice: 896,
    onSale: false,
    NewArrival: true,
    cate: "Kids",
  },
  {
    id: 19,
    name: "Baby Shirt",
    Image: BabyShirt,
    price: 323,
    oldPrice: 524,
    onSale: true,
    NewArrival: false,
    cate: "Kids",
  },
  {
    id: 20,
    name: "Kids Sweater",
    Image: Sweater,
    price: 524,
    oldPrice: 772,
    onSale: false,
    NewArrival: true,
    cate: "Kids",
  },
  {
    id: 21,
    name: "Baby Dress",
    Image: Dress,
    price: 572,
    oldPrice: 896,
    onSale: true,
    NewArrival: false,
    cate: "Kids",
  },
  {
    id: 22,
    name: "Printed T-shirt",
    Image: TShirt,
    price: 473,
    oldPrice: 647,
    onSale: false,
    NewArrival: true,
    cate: "Kids",
  },
  {
    id: 23,
    name: "Baby Skater",
    Image: Skater,
    price: 498,
    oldPrice: 722,
    onSale: true,
    NewArrival: false,
    cate: "Kids",
  },
  {
    id: 24,
    name: "Kids Shirt",
    Image: Shirt,
    price: 547,
    oldPrice: 822,
    onSale: false,
    NewArrival: true,
    cate: "Kids",
  },

  // ---------- New Arrivals ----------
  {
    id: 25,
    name: "New Arrival Hoodie",
    Image: Hoodie,
    price: 1394,
    oldPrice: 1767,
    onSale: false,
    NewArrival: true,
    cate: "New Arrivals",
  },
  {
    id: 26,
    name: "New Arrival Leather Jacket",
    Image: LeatherJacket,
    price: 3735,
    oldPrice: 4482,
    onSale: false,
    NewArrival: true,
    cate: "New Arrivals",
  },
  {
    id: 27,
    name: "New Arrival Dress",
    Image: Dress,
    price: 1643,
    oldPrice: 2141,
    onSale: false,
    NewArrival: true,
    cate: "New Arrivals",
  },
  {
    id: 28,
    name: "New Arrival Skater",
    Image: Skater,
    price: 1020,
    oldPrice: 1394,
    onSale: false,
    NewArrival: true,
    cate: "New Arrivals",
  },
  {
    id: 29,
    name: "New Arrival Shirt",
    Image: Shirt,
    price: 896,
    oldPrice: 1269,
    onSale: false,
    NewArrival: true,
    cate: "New Arrivals",
  },
  {
    id: 30,
    name: "New Arrival Skirt",
    Image: Skirt,
    price: 772,
    oldPrice: 1145,
    onSale: false,
    NewArrival: true,
    cate: "New Arrivals",
  },
  {
    id: 31,
    name: "New Arrival T-shirt",
    Image: TShirt,
    price: 722,
    oldPrice: 971,
    onSale: false,
    NewArrival: true,
    cate: "New Arrivals",
  },
  {
    id: 32,
    name: "New Arrival Sweater",
    Image: Sweater,
    price: 1220,
    oldPrice: 1643,
    onSale: false,
    NewArrival: true,
    cate: "New Arrivals",
  },

  // ---------- On Sale ----------
  {
    id: 33,
    name: "On Sale Jeans",
    Image: Jeans,
    price: 597,
    oldPrice: 929,
    onSale: true,
    NewArrival: false,
    cate: "On Sale",
  },
  {
    id: 34,
    name: "On Sale Hoodie",
    Image: Hoodie,
    price: 680,
    oldPrice: 1012,
    onSale: true,
    NewArrival: false,
    cate: "On Sale",
  },
  {
    id: 35,
    name: "On Sale Leather Jacket",
    Image: LeatherJacket,
    price: 1840,
    oldPrice: 2506,
    onSale: true,
    NewArrival: false,
    cate: "On Sale",
  },
  {
    id: 36,
    name: "On Sale Skirt",
    Image: Skirt,
    price: 431,
    oldPrice: 680,
    onSale: true,
    NewArrival: false,
    cate: "On Sale",
  },
  {
    id: 37,
    name: "On Sale Dress",
    Image: Dress,
    price: 763,
    oldPrice: 1178,
    onSale: true,
    NewArrival: false,
    cate: "On Sale",
  },
  {
    id: 38,
    name: "On Sale Shirt",
    Image: Shirt,
    price: 381,
    oldPrice: 597,
    onSale: true,
    NewArrival: false,
    cate: "On Sale",
  },
  {
    id: 39,
    name: "On Sale T-shirt",
    Image: TShirt,
    price: 315,
    oldPrice: 481,
    onSale: true,
    NewArrival: false,
    cate: "On Sale",
  },
  {
    id: 40,
    name: "On Sale Sweater",
    Image: Sweater,
    price: 515,
    oldPrice: 846,
    onSale: true,
    NewArrival: false,
    cate: "On Sale",
  },

  // ---------- Extras ----------
  {
    id: 41,
    name: "Casual Hoodie",
    Image: Hoodie,
    price: 714,
    oldPrice: 929,
    onSale: false,
    NewArrival: false,
    cate: "Mens",
  },
  {
    id: 42,
    name: "Office Shirt",
    Image: Shirt,
    price: 481,
    oldPrice: 647,
    onSale: false,
    NewArrival: false,
    cate: "Mens",
  },
  {
    id: 43,
    name: "Slim Skirt",
    Image: Skirt,
    price: 415,
    oldPrice: 597,
    onSale: true,
    NewArrival: false,
    cate: "Women",
  },
  {
    id: 44,
    name: "Party Dress",
    Image: Dress,
    price: 1012,
    oldPrice: 1336,
    onSale: false,
    NewArrival: false,
    cate: "Women",
  },
  {
    id: 45,
    name: "Winter Skater",
    Image: Skater,
    price: 597,
    oldPrice: 846,
    onSale: true,
    NewArrival: false,
    cate: "Women",
  },
  {
    id: 46,
    name: "Baby Hoodie",
    Image: Hoodie,
    price: 381,
    oldPrice: 530,
    onSale: false,
    NewArrival: false,
    cate: "Kids",
  },
  {
    id: 47,
    name: "Baby Jeans",
    Image: Jeans,
    price: 331,
    oldPrice: 481,
    onSale: true,
    NewArrival: false,
    cate: "Kids",
  },
  {
    id: 48,
    name: "Baby Sweater",
    Image: Sweater,
    price: 350,
    oldPrice: 515,
    onSale: false,
    NewArrival: false,
    cate: "Kids",
  },
  {
    id: 49,
    name: "Street Style Jacket",
    Image: LeatherJacket,
    price: 2158,
    oldPrice: 2656,
    onSale: false,
    NewArrival: false,
    cate: "Mens",
  },
  {
    id: 50,
    name: "Basic T-shirt",
    Image: TShirt,
    price: 265,
    oldPrice: 431,
    onSale: true,
    NewArrival: false,
    cate: "Mens",
  },
];

export default products;
